[0m05:44:50.564409 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b30af2f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b2f90c430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b2f90c3d0>]}


============================== 05:44:50.569186 | 16bf41c1-9ff6-4e0a-8f7a-effef2dfed22 ==============================
[0m05:44:50.569186 [info ] [MainThread]: Running with dbt=1.10.13
[0m05:44:50.570094 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'profiles_dir': '/home/ubuntu/.dbt', 'debug': 'False', 'log_path': 'logs', 'partial_parse': 'True', 'printer_width': '80', 'empty': 'None', 'introspect': 'True', 'quiet': 'False', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'cache_selected_only': 'False', 'version_check': 'True', 'indirect_selection': 'eager', 'use_colors': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'fail_fast': 'False', 'log_format': 'default', 'target_path': 'None', 'use_experimental_parser': 'False', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m05:44:57.111968 [debug] [MainThread]: Starter project path: /home/ubuntu/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m05:44:57.116385 [info ] [MainThread]: 
Your new dbt project "book_app" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m05:44:57.117423 [info ] [MainThread]: Setting up your profile.
[0m05:47:32.855297 [info ] [MainThread]: Profile book_app written to /home/ubuntu/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m05:47:32.863428 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 162.3885, "process_in_blocks": "42208", "process_kernel_time": 0.918811, "process_mem_max_rss": "332296", "process_out_blocks": "80", "process_user_time": 5.122579}
[0m05:47:32.865205 [debug] [MainThread]: Command `dbt init` succeeded at 05:47:32.864881 after 162.39 seconds
[0m05:47:32.866102 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b30af2f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b11de5de0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9b11de5780>]}
[0m05:47:32.866961 [debug] [MainThread]: Flushing usage events
[0m05:47:34.092114 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:54:23.600606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a98baef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a8628550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a86284f0>]}


============================== 05:54:23.606712 | 42906e76-133a-4d6f-a396-4dde23bb51d6 ==============================
[0m05:54:23.606712 [info ] [MainThread]: Running with dbt=1.10.13
[0m05:54:23.607910 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'write_json': 'True', 'quiet': 'False', 'printer_width': '80', 'invocation_command': 'dbt seed', 'introspect': 'True', 'version_check': 'True', 'log_format': 'default', 'cache_selected_only': 'False', 'empty': 'None', 'use_experimental_parser': 'False', 'profiles_dir': '/home/ubuntu/.dbt', 'warn_error': 'None', 'log_path': 'logs', 'use_colors': 'True', 'debug': 'False', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'partial_parse': 'True', 'static_parser': 'True', 'no_print': 'None', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m05:54:23.609251 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/project/book-app/analytics/dbt_book-app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:54:23.611563 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 0.13220659, "process_in_blocks": "12664", "process_kernel_time": 0.221371, "process_mem_max_rss": "94656", "process_out_blocks": "16", "process_user_time": 2.33291}
[0m05:54:23.613017 [debug] [MainThread]: Command `dbt seed` failed at 05:54:23.612766 after 0.13 seconds
[0m05:54:23.613938 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a98baef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a8628c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc5a8628550>]}
[0m05:54:23.614914 [debug] [MainThread]: Flushing usage events
[0m05:54:25.334119 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:38:53.510597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c96c96fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c95ab8670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c95ab8610>]}


============================== 06:38:53.517812 | 23add1a4-a93c-47f8-aef7-7802204af5c0 ==============================
[0m06:38:53.517812 [info ] [MainThread]: Running with dbt=1.10.13
[0m06:38:53.519107 [debug] [MainThread]: running dbt with arguments {'invocation_command': 'dbt run --select datamart', 'fail_fast': 'False', 'indirect_selection': 'eager', 'static_parser': 'True', 'use_colors': 'True', 'log_format': 'default', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'target_path': 'None', 'empty': 'False', 'send_anonymous_usage_stats': 'True', 'log_cache_events': 'False', 'introspect': 'True', 'log_path': 'logs', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/home/ubuntu/.dbt', 'use_experimental_parser': 'False', 'printer_width': '80', 'quiet': 'False', 'write_json': 'True', 'no_print': 'None', 'partial_parse': 'True', 'version_check': 'True'}
[0m06:38:53.520309 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/project/book-app/analytics/dbt_book-app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:38:53.523070 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.1133335, "process_in_blocks": "88408", "process_kernel_time": 0.500833, "process_mem_max_rss": "94928", "process_out_blocks": "8", "process_user_time": 2.495061}
[0m06:38:53.524560 [debug] [MainThread]: Command `dbt run` failed at 06:38:53.524280 after 0.12 seconds
[0m06:38:53.525518 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c96c96fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c95ab8d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8c95ab8670>]}
[0m06:38:53.526538 [debug] [MainThread]: Flushing usage events
[0m06:38:55.445254 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:40:40.328918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283e4def50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283d2fc5e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283d2fc580>]}


============================== 06:40:40.334380 | 023accf1-e866-48f9-973b-eecd2c8b70f9 ==============================
[0m06:40:40.334380 [info ] [MainThread]: Running with dbt=1.10.13
[0m06:40:40.335746 [debug] [MainThread]: running dbt with arguments {'cache_selected_only': 'False', 'use_colors': 'True', 'printer_width': '80', 'write_json': 'True', 'invocation_command': 'dbt run --select datamart', 'log_format': 'default', 'log_cache_events': 'False', 'log_path': 'logs', 'empty': 'False', 'static_parser': 'True', 'fail_fast': 'False', 'debug': 'False', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'indirect_selection': 'eager', 'no_print': 'None', 'use_experimental_parser': 'False', 'target_path': 'None', 'quiet': 'False', 'warn_error': 'None', 'introspect': 'True', 'profiles_dir': '/home/ubuntu/.dbt'}
[0m06:40:40.337207 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/project/book-app/analytics/dbt_book-app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:40:40.339676 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.13388087, "process_in_blocks": "5360", "process_kernel_time": 0.187992, "process_mem_max_rss": "95400", "process_out_blocks": "8", "process_user_time": 2.55424}
[0m06:40:40.341019 [debug] [MainThread]: Command `dbt run` failed at 06:40:40.340756 after 0.14 seconds
[0m06:40:40.342054 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283e4def50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283d2fcd00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f283d2fc5e0>]}
[0m06:40:40.343220 [debug] [MainThread]: Flushing usage events
[0m06:40:41.523811 [debug] [MainThread]: An error was encountered while trying to flush usage events
